#!/bin/bash

_DEBUG_ON=false

# NOTE: GID 20 is staff group -- see more with: dscl ${OSXDS} list groups gid
DEFAULT_GID=20
DEFAULT_GROUP=staff
DEFAULT_SHELL=/bin/bash
DEFAULT_HOME_BASE=/Users

# Data Source for DSCL
#OSXDS="."
OSXDS="localhost"

me=$(basename $0)

log()  { printf "$*\n" ; return $? ;  }
fail() { log "\nERROR: $*\n" ; exit 1 ; }

usage() {
  printf "
Usage  
  $me <username>

Note: Probably have to run with sudo
"
  #$me <username> [-home <path>] [-uid <id>] [-gid <id>] [-shell <path>]
}

_delete_user() {
  target_user="$1"
  target_home="$2"
  target_shell="$3"
  target_uid="$4"
  target_gid="$5"
  target_name="$6"

  OSX_USER="/Users/$target_user"
  dscl ${OSXDS} -delete "${OSX_USER}" NFSHomeDirectory  && \
    dscl ${OSXDS} -delete "${OSX_USER}" UserShell  && \
    dscl ${OSXDS} -delete "${OSX_USER}" UniqueID  && \
    dscl ${OSXDS} -delete "${OSX_USER}" PrimaryGroupID  && \
    ( [ ! -z "$target_name" ] &&  dscl ${OSXDS} -delete "${OSX_USER}" RealName  ) && \
    dscl ${OSXDS} -delete "${OSX_USER}"
  return $?
}

# TODO: accept more options
if [ -z "$1" ] ; then
  usage
  exit 0
fi

target_user="$1"
target_shell=$DEFAULT_SHELL
target_uid=$(($(dscl ${OSXDS} -list /Users uid | sort -nk2 | tail -n 1 | awk '{print $2}')+1))
target_gid=${DEFAULT_GID}
target_name="Marry Poppins $RANDOM"
home_base=$DEFAULT_HOME_BASE
target_home="${home_base}/$target_user"
target_group="${DEFAULT_GROUP}"

eval $(dscl ${OSXDS} read /Users/$target_user | grep -Ev '^ |RealName' | sed 's/: /=/')
eval $(dscl ${OSXDS} read /Users/$target_user RealName | tr -d '\n' | sed 's/: /="/;s/$/"/')

target_home=${NFSHomeDirectory}
target_gid=${PrimaryGroupID}
target_uid=${UniqueID}
target_shell=${UserShell}
target_name=${RealName}



echo -e "Attempting to delete $target_user with attributes\n\thome: $target_home, shell: $target_shell uid: $target_uid gid: $target_gid name: $target_name" |fmt

[ "$_DEBUG_ON" = true ] && set -x
_delete_user "$target_user" "$target_home" "$target_shell" "$target_uid" "$target_gid" "$target_name"

[ "$?" = 0 ] && log "You should remove ${target_home} now"

set +x
